### ISSUE TITLE
Como desenvolvedor/gerente quero criar um KRON job

### ISSUE THREAD

**Issue by rafael-g-depaulo** [rafael-g-depaulo/labfaz#1]
Como gerente e/ou desenvolvedor, eu quero poder criar um KRON job por meio de uma adição na codebase.

Esse KRON job deve poder interagir com o banco de dados principal da API, e fazer requisições HTTP para o strapi (informações de conexão com o strapi devem ser extraídas de ```"@labfaz/server-conn-info"```

A decisão entre acoplar essa funcionalidade com o apps/api ou criar um novo app na infraestrutura é do desenvolvedor que for implementar essa feature

**Comment by icaronr** [comment]
Bibliotecas que serão utilizadas:
Para fazer o 'agendamento':
https://www.npmjs.com/package/node-cron
Para fazer o parsing dos crons cadastrados e utilizar em logs, reports ou views.
https://www.npmjs.com/package/cronstrue
