### ISSUE TITLE
Como usuário não-cadastrado, quero entrar no site e visualizar o Header e baixo o Banner

### ISSUE THREAD

**Issue by Jaxiii** [rafael-g-depaulo/labfaz#12]
#### Da esquerda para a direita - Header contem:
1.  Logo (Imagem), que deve ter um hyperlink que leva o usuário de volta a [Home];
2.  Quem Somos (Texto - hyperlink), que deve ter um hyperlink que leva o usuário a pagina [Quem Somos];
3.  Cursos (Texto - hyperlink), que deve ter um hyperlink que leva o usuário a pagina [Cursos];
4. (?) Agenda (Texto - hyperlink), que deve ter um hyperlink que leva o usuário a pagina [Agenda];
5.  Blog (Texto - hyperlink), que deve ter um hyperlink que leva o usuário a pagina [Blog];
6.  Banco de Profissionais (Texto - hyperlink), que deve ter um hyperlink que leva o usuário a pagina [Banco de Profissionais];
7.  Divider (Divider - vertical), que deve separar os hyperlinks anteriores dos [Botões] que vem a seguir;
8.  Entrar (Botão - hyperlink), que deve ter um hyperlink que leva o usuário a pagina [Login];
9.  Cadastre-se (Botão - hyperlink), que deve ter um hyperlink que leva o usuário a pagina [Cadastro];
	
#### De cima para baixo - Banner contem:
1. Titulo (Texto - H1), que deve apresentar um [Titulo - H1] em texto estático;
2.  Subtítulo (Texto - H2), que deve apresentar um [Subtítulo - H2] em texto estático;
3.  Saiba-mais (Botão - hyperlink), que deve ter um hyperlink que leva o usuário a um pagina ainda a ser decidida;
4. (!) Banner (Imagem), deve ficar estática atrás do demais componentes acima, [z-index inferior] 

#### Instruções detalhadas de design podem ser visualizadas no Figma pelos links:
* [Prototype] -> https://www.figma.com/proto/emttN5ixP7k3kw6b4F6zMW/Wireframe?node-id=70%3A0&viewport=-1461%2C-101%2C0.25070920586586&scaling=scale-down
* [Layout] -> https://www.figma.com/file/emttN5ixP7k3kw6b4F6zMW/Wireframe?node-id=0%3A1

<h4 align="center">Imagem Exemplo Web:</h4>

![Imagem exemplo:](https://i.imgur.com/l3a6hko.png)

<h4 align="center">Imagem Exemplo Mobile:</h4>

![Imagem exemplo:](https://i.imgur.com/eWJtb0Q.png)

### __________________________________________________________________________________________________________
<h2 align="center">User Interface - UI</h4>

<h4 align="center">Figma:</h4>
<h4 align="center">Pasta "UI"</h4>
<h4 align="center">Arquivo "Scaled UI Components"</h4>

<h4 align="center">Imagem Exemplo Web com UI:</h4>

![Imagem exemplo:](https://i.imgur.com/HGRlTN7.png)

Fonte de Texto: Cairo
https://fonts.google.com/specimen/Cairo

Cores e Tamanho dos Textos estão no Figma e nos próprios componentes.

As margens e paddings podem ser vistos usando o ALT + Ponteiro do Mouse sobre os Componentes no Figma

<h4 align="center">Imagem Exemplo de como visualizar distancia entre componentes:</h4>

![Imagem exemplo:](https://i.imgur.com/HjVwQYh.png)

Demais informações podem ser encontradas no Figma, inspecionando os componentes.

<h4 align="center">Imagem Exemplo de como inspecionar componentes:</h4>

![Imagem exemplo:](https://i.imgur.com/0wzbltU.png)

![Imagem exemplo:](https://i.imgur.com/vhwqzJW.png)

**Comment by priscila-eng** [comment]
Fiz o esqueleto, mas não coloquei as imagens, deixei o espaço e alguns estilos comentados que talvez precisarão. Vou abrir o PR para review.

**Comment by priscila-eng** [comment]
@rafael-g-depaulo Já adicionei responsividade.

**Comment by Jaxiii** [comment]
Adicionado versão mobile. 
O Query de media pode seguir o Width do Figma para Android e iOS, e/ou detectar plataforma. Fica a cargo de vocês decidirem a melhor forma de implementar responsividade.

**Comment by Jaxiii** [comment]
Adicionado versão Web com UI.

**Comment by Jaxiii** [comment]
[**ALTERAÇÃO**]  
Novo link no Header, vou colocar como request change no PR #51.

![](https://i.imgur.com/YzN3zSG.png)
