### ISSUE TITLE
Emails com o domínio @labfaz

### ISSUE THREAD

**Issue by rafael-g-depaulo** [rafael-g-depaulo/labfaz#13]
A coordenação pediu se podemos criar emails com @labfaz como domínio. Em teoria não tem limitação de ferramenta, serviço ou método para conseguir isso, mas vamos levar em conta o custo associado.

O domínio ainda não foi comprado para ser flexível se tiver algum serviço de aluguel de domínio que facilite com a criação dos emails e valha a pena.

**Comment by Zipudhe** [comment]
Por enquanto em questão de serviços, fora o da própria google, o serviço da [fowardemail](https://forwardemail.net/pt) tem opções bem interessante de preços.

**Comment by Zipudhe** [comment]
Fiz um teste, peguei um domínio na hostinger e achei bem tranquilo para fazer a configuração de dns. E utilizando o plano grátis do [fowardemail](https://forwardemail.net/pt/pricing) acho que resolve essa questão, a menos para uma área de contato que precise subir muitos assets, nesse caso o plano grátis não contenplaria a gente por ter um limite de 50 MB de assets. O plano mais básico, que já não tem esse limite, fica 180 reais ao ano.
