### ISSUE TITLE
Como usuário não-cadastrado, após entrar no site e ver o Header e o Banner da Home quero descer na página e visualizar o Componente de Apresentação, com player de video, título e texto 

### ISSUE THREAD

**Issue by Jaxiii** [rafael-g-depaulo/labfaz#17]
#### Da esquerda para a direita - Componente de Vídeo/Apresentação contém:
1. Player de Video, que deve iniciar um vídeo ao ser clicado pelo usuário; (Podemos usar o player padrão do youtube por enquanto)
2.  Componente em Bloco de Texto (componente completo abaixo)

#### De cima para baixo - Componente em Bloco de Texto contém:
1. Título com alinhado à esquerda
2. Parágrafo com formatação de alinhamento a esquerda

**OBS**:  fonte, tamanho da fonte, imagem da logo, e paleta de cores ainda estão em estágio de aprovação pela coordenação. 
      Portanto recomendo seguir o padrão de design Wireframe que está atualmente no Figma.

#### Instruções detalhadas de design podem ser visualizadas no Figma pelos links:
* [Prototype] -> https://www.figma.com/proto/emttN5ixP7k3kw6b4F6zMW/Wireframe?page-id=0%3A1&node-id=70%3A0&viewport=-1104%2C-411%2C0.20185048878192902&scaling=scale-down
    
* [Layout] -> https://www.figma.com/file/emttN5ixP7k3kw6b4F6zMW/Wireframe?node-id=70%3A0

<h4 align="center">Imagem Exemplo:</h4>

![Imagem exemplo:](https://i.imgur.com/Ybh4Oym.png)

### __________________________________________________________________________________________________________
<h2 align="center">User Interface - UI</h4>

<h4 align="center">Figma:</h4>
<h4 align="center">Pasta "UI"</h4>
<h4 align="center">Arquivo "Scaled UI Components"</h4>

<h4 align="center">Imagem Exemplo Web com UI:</h4>

![Imagem exemplo:](https://i.imgur.com/pRGLuEh.png)

<h4 align="center">Imagem Exemplo Mobile com UI:</h4>

![Imagem exemplo:](https://i.imgur.com/sTZHofm.png)

Fonte de Texto: Cairo
https://fonts.google.com/specimen/Cairo

Cores e Tamanho dos Textos estão no Figma e nos próprios componentes.

As margens e paddings podem ser vistos usando o ALT + Ponteiro do Mouse sobre os Componentes no Figma

<h4 align="center">Imagem Exemplo de como visualizar distancia entre componentes:</h4>

![Imagem exemplo:](https://i.imgur.com/HjVwQYh.png)

Demais informações podem ser encontradas no Figma, inspecionando os componentes.

<h4 align="center">Imagem Exemplo de como inspecionar componentes:</h4>

![Imagem exemplo:](https://i.imgur.com/0wzbltU.png)

![Imagem exemplo:](https://i.imgur.com/vhwqzJW.png)

**Comment by priscila-eng** [comment]
Tentei utilizar a tag video do html para renderizar, mas não funcionou. Estou pensando em utilizar uma biblioteca do react, essa daqui: https://github.com/CookPete/react-player parece funcionar.

**Comment by priscila-eng** [comment]
> Tentei utilizar a tag video do html para renderizar, mas não funcionou. Estou pensando em utilizar uma biblioteca do react, essa daqui: https://github.com/CookPete/react-player parece funcionar.

Eu testei e funciona, mas fiquei na dúvida se adiciono nas devDependencies ou dependencies? @rafael-g-depaulo

**Comment by rafael-g-depaulo** [comment]
a gente só vai usar vídeos do youtube no app, e com isso eu recomendo usar a biblioteca 'react-youtube'. [aqui tem um exemplo de quando eu usei essa lib em outro projeto](https://github.com/rafael-g-depaulo/plural-app/blob/develop/client/src/Components/Markdown/Link/YoutubePlayer.js)

**Comment by rafael-g-depaulo** [comment]
No componente que você for criar eu recomendo ter width e height padrão, mas também receber parâmetros opcionais para poder re-escrever esse default se a situação permitir. Como o player do youtube só permite tamanho em pixels, tome cuidado com telas pequenas, e faça testes (não testes unitários, mas experimente mesmo visualmente) testando o uso do componente com ou sem os parâmetros de tamanho em telas pequenas e grandes

**Comment by priscila-eng** [comment]
Eu testei a componente de vídeo passando width e height, passando só width, passando só height e não passando nada. Funciona do mesmo jeito. Mas o tamanho default é muito grande para página home, então diminui o tamanho da componente passando diferentes tamanhos de width e height. Testei a responsividadade para telas maiores e iguais que 768px, menor que isso fica muito quebrado e teria que diminuir a componente de vídeo mais ainda e ficaria ruim de ver porque tem aquelas ferramentas default do youtube.

**Comment by Jaxiii** [comment]
UI Update.
Comentário Inicial do Issue atualizado com UI.
