### ISSUE TITLE
Como usuário não-cadastrado, após entrar no site e ver o Header, Banner da Home, Componente de Apresentação, desejo descer mais na página e ver o Componente de Parceiros Apoiadores

### ISSUE THREAD

**Issue by Jaxiii** [rafael-g-depaulo/labfaz#18]
#### Da cima para baixo o Componente de Parceiros Apoiadores contém:
1. Título (OBS: Definir com o Rafa qual tag HTML usar por questões de indexação dos mecanismo de busca)
2. Banner, contendo a logo dos parceiros apoiadores

#### O Banner contém:
1. Logo dos apoiadores, de preferência com as imagens das logos centralizadas, visto que não sabemos a quantidade de apoiadores no momento

**OBS**:  fonte, tamanho da fonte, imagem da logo, e paleta de cores ainda estão em estágio de aprovação pela coordenação. 
      Portanto recomendo seguir o padrão de design Wireframe que está atualmente no Figma.

#### Instruções detalhadas de design podem ser visualizadas no Figma pelos links:
* [Prototype] -> https://www.figma.com/proto/emttN5ixP7k3kw6b4F6zMW/Wireframe?page-id=0%3A1&node-id=70%3A0&viewport=-1104%2C-411%2C0.20185048878192902&scaling=scale-down
* [Layout] -> https://www.figma.com/file/emttN5ixP7k3kw6b4F6zMW/Wireframe?node-id=70%3A0

<h4 align="center">Imagem Exemplo:</h4>

![Imagem exemplo:](https://i.imgur.com/pDtFoQC.png)

### __________________________________________________________________________________________________________
<h2 align="center">User Interface - UI</h4>

<h4 align="center">Figma:</h4>
<h4 align="center">Pasta "UI"</h4>
<h4 align="center">Arquivo "Scaled UI Componentes"</h4>
<a href="https://www.figma.com/file/W2ZMhVYN1Q2AHyoLOpCfYF/Scaled-UI-and-Components"><h4 align="center">https://www.figma.com/file/W2ZMhVYN1Q2AHyoLOpCfYF/Scaled-UI-and-Components</h4></a>

<h4 align="center">Imagem Exemplo Web com UI:</h4>

![Imagem exemplo:](https://i.imgur.com/ydXjqpn.png)

<h4 align="center">Imagem Exemplo Mobile com UI:</h4>

![Imagem exemplo:](https://i.imgur.com/YWT5lls.png)

Fonte de Texto: Cairo
https://fonts.google.com/specimen/Cairo

Cores e Tamanho dos Textos estão no Figma e nos próprios componentes.

As margens e paddings podem ser vistos usando o ALT + Ponteiro do Mouse sobre os Componentes no Figma

<h4 align="center">Imagem Exemplo de como visualizar distancia entre componentes:</h4>

![Imagem exemplo:](https://i.imgur.com/HjVwQYh.png)

Demais informações podem ser encontradas no Figma, inspecionando os componentes.

<h4 align="center">Imagem Exemplo de como inspecionar componentes:</h4>

![Imagem exemplo:](https://i.imgur.com/0wzbltU.png)

![Imagem exemplo:](https://i.imgur.com/vhwqzJW.png)

**Comment by priscila-eng** [comment]
@rafael-g-depaulo quando puder, pode me dizer qual tag html utilizar no título?

**Comment by Jaxiii** [comment]
> @rafael-g-depaulo quando puder, pode me dizer qual tag html utilizar no título?

Eu deixei em aberto porque eu não tenho muito conhecimento de indexação de buscas @rafael-g-depaulo, e o design geral das tags podem ser alterados pelos css. Podemos nos reunir pra ver isso caso precise.

**Comment by Jaxiii** [comment]
UI Update.
Comentário inicial do Issue atualizado, UI adicionada.
