### ISSUE TITLE
Checar se dá problema fazer o app nativo usando o player do youtube

### ISSUE THREAD

**Issue by rafael-g-depaulo** [rafael-g-depaulo/labfaz#25]

**Comment by icaronr** [comment]
@rafael-g-depaulo você tinha comentado sobre uma biblioteca pra inserir o embed player no react. encontrei essas duas libs que são bem utilizadas: [react-youtube](https://www.npmjs.com/package/react-youtube) e [react-player](https://www.npmjs.com/package/react-player). 

Vou testar as 2 e trago os resultados.

**Comment by rafael-g-depaulo** [comment]
> @rafael-g-depaulo você tinha comentado sobre uma biblioteca pra inserir o embed player no react. encontrei essas duas libs que são bem utilizadas: [react-youtube](https://www.npmjs.com/package/react-youtube) e [react-player](https://www.npmjs.com/package/react-player).
> 
> Vou testar as 2 e trago os resultados.

A gente está usando o react-youtube no projeto já. Se der certo com essa tá ótimo já

**Comment by icaronr** [comment]
O react-yourube funciona de boas.
Configurei pra gente conseguir filtrar por domínio e por url também. O problema do filtro por url é como a gente passaria as urls dos vídeos pra lista que fica no app...
Enfim, configurado da forma que ficou, ele aceita páginas que estão nas urls especificadas, aí quando tenta acessar uma coisa que não tá, ele abre no navegador, upei esse [vídeo aqui](https://youtu.be/6N9eHDFbANI) pra mostrar mais ou menos o que rola.
