### ISSUE TITLE
Como usuário não-cadastrado, quero entrar na página do Blog e ao rolar para baixo do Banner desejo ver uma chamada para um Post

### ISSUE THREAD

**Issue by Jaxiii** [rafael-g-depaulo/labfaz#28]
#### De cima para baixo - O de Chamada para Post do Blog Contém:

1. Título (h1)
1.2 Divisor a direita (A direita de 1. e a cima de 2 e 3.. - tag html hr seria bom, mas não é obrigatório)
1.3 Data de publicação, Dia em Cima, Hora em Baixo (Texto) (Esse componente sofrerá um rework no futuro, para datas após 1 semana de publicação)
2. Resumo/Parágrafo Inicial/Chamada (Texto)
3. Imagem (Pode ter ou não, é opcional, mas coloque para efeito prático até a integração com o back) 

**OBS**:  Alguns artifícios de design ainda estão em estágio de aprovação pela coordenação. 
      Portanto recomendo seguir o padrão de design Wireframe que está atualmente no Figma.

**OBS 2**:  Note que no Figma as chamadas podem ou não ter imagem, isso deverá ser feito com alguma lógica entre o back e o front. Porem o componente deve existir como um todo e completo como na imagem exemplo.

#### Instruções detalhadas de design podem ser visualizadas no Figma pelos links:
* [Prototype] -> https://www.figma.com/proto/emttN5ixP7k3kw6b4F6zMW/Wireframe?node-id=239%3A76&scaling=scale-down&page-id=0%3A1
* [Layout] -> https://www.figma.com/file/emttN5ixP7k3kw6b4F6zMW/Wireframe?node-id=239%3A76

<h4 align="center">Imagem Exemplo:</h4>

![Imagem exemplo:](https://i.imgur.com/Ze8YyRI.png)
### __________________________________________________________________________________________________________
<h2 align="center">User Interface - UI</h4>

<h4 align="center">Figma:</h4>
<h4 align="center">Pasta "UI"</h4>
<h4 align="center">Arquivo "Scaled UI Components"</h4>
<a  href="https://www.figma.com/file/W2ZMhVYN1Q2AHyoLOpCfYF/Scaled-UI-and-Components?node-id=0%3A1"><h4 align="center">https://www.figma.com/file/W2ZMhVYN1Q2AHyoLOpCfYF/Scaled-UI-and-Components?node-id=0%3A1</h4></a>

<h4 align="center">Imagem Exemplo Web com UI:</h4>

![Imagem exemplo:](https://i.imgur.com/5ekluZf.png)

<h4 align="center">Imagem Exemplo Mobile com UI:</h4>

![Imagem exemplo:](https://i.imgur.com/dbR5YdY.png)

Fonte de Texto: Cairo
https://fonts.google.com/specimen/Cairo

Cores e Tamanho dos Textos estão no Figma e nos próprios componentes.

As margens e paddings podem ser vistos usando o ALT + Ponteiro do Mouse sobre os Componentes no Figma

<h4 align="center">Imagem Exemplo de como visualizar distância entre componentes:</h4>

![Imagem exemplo:](https://i.imgur.com/HjVwQYh.png)

Demais informações podem ser encontradas no Figma, inspecionando os componentes.

<h4 align="center">Imagem Exemplo de como inspecionar componentes:</h4>

![Imagem exemplo:](https://i.imgur.com/0wzbltU.png)

![Imagem exemplo:](https://i.imgur.com/vhwqzJW.png)

**Comment by clarice42** [comment]
Na data, deve aparecer para o usuário o dia da semana em que foi criado o post? Ou só a data no estilo 12/12/12?

**Comment by rafael-g-depaulo** [comment]
> Na data, deve aparecer para o usuário o dia da semana em que foi criado o post? Ou só a data no estilo 12/12/12?

espera o @Jaxiii confirmar que ele que definiu isso, mas eu imagino onde tem um "today" na UI vc coloca:
  1. "hoje", se o dia de edição/criação do post for hoje
  2. o dia da semana da edição/criação do post em português, se o dia de edição/criação do post foi de até uma semana atrás
  3. ainda o caso 2. se for mais antigo que isso? ou faz sentido colocar outra coisa tipo "x semanas atrás" ou "antigo"?

**Comment by Jaxiii** [comment]
UI Update.
Comentário inicial atualizado com a UI

Em relação a:

 https://github.com/rafael-g-depaulo/labfaz/issues/28#issuecomment-869074385

> > Na data, deve aparecer para o usuário o dia da semana em que foi criado o post? Ou só a data no estilo 12/12/12?
> 
> espera o @Jaxiii confirmar que ele que definiu isso, mas eu imagino onde tem um "today" na UI vc coloca:
> 
> 1. "hoje", se o dia de edição/criação do post for hoje
> 2. o dia da semana da edição/criação do post em português, se o dia de edição/criação do post foi de até uma semana atrás
> 3. ainda o caso 2. se for mais antigo que isso? ou faz sentido colocar outra coisa tipo "x semanas atrás" ou "antigo"?

Eu adicionei um padrão no layout do blog do Figma para as datas de publicação, vejam se é tranquilo de implementar desse jeito, se não me avisem que eu penso em outra coisa.
