### ISSUE TITLE
Como usuário não-cadastrado, quero poder me cadastrar (back)

### ISSUE THREAD

**Issue by rafael-g-depaulo** [rafael-g-depaulo/labfaz#3]
Como usuário não-cadastrado, quero poder me cadastrar chamando a rota equivalente da api.

Eu preciso mandar as seguintes informações:

- A SER DEFINIDO. NÃO RECEBEMOS AINDA DA COORDENAÇÃO QUAIS INFORMAÇÕES DO USUÁRIO DEVEM SER ARMAZENADAS

**Comment by IcaroRodrigues** [comment]
Como não foi definido as informações que serão armazenadas do usuário, irei fazer o cadastro com as informações mais simples e essenciais, como nome, e-mail e senha.
