### ISSUE TITLE
Como usuário não-cadastrado, quero entrar na página do Quem Somos e ao rolar para baixo do Banner desejo ver a Imagem e o Texto de Introdução

### ISSUE THREAD

**Issue by Jaxiii** [rafael-g-depaulo/labfaz#30]
#### Da esquerda para direita - Componente de Introdução do Quem Somos Contém:
1. Imagem de Introdução (Imagem)
2. Parágrafos:
2.1 Parágrafo 1 (acima do Parágrafo 2, separado pelo espaçamento definido no Figma)
2.2 Parágrafo 2 (abaixo do Parágrafo 1, separado pelo espaçamento definido no Figma)

**OBS**: Alguns artifícios de design ainda estão em estágio de aprovação pela coordenação.
Portanto recomendo seguir o padrão de design Wireframe que está atualmente no Figma.

#### Instruções detalhadas de design podem ser visualizadas no Figma pelos links:

* [Prototype] -> https://www.figma.com/proto/emttN5ixP7k3kw6b4F6zMW/Wireframe?node-id=239%3A76&scaling=scale-down&page-id=0%3A1
* [Layout] -> https://www.figma.com/file/emttN5ixP7k3kw6b4F6zMW/Wireframe?node-id=239%3A76

<h4 align="center">Imagem Exemplo:</h4>

![Imagem exemplo:](https://i.imgur.com/w5GBnk9.png)

### __________________________________________________________________________________________________________
<h2 align="center">User Interface - UI</h4>

<h4 align="center">Figma:</h4>
<h4 align="center">Pasta "UI"</h4>
<h4 align="center">Arquivo "Scaled UI Componentes"</h4>
<h4 align="center" ><a href="https://www.figma.com/file/W2ZMhVYN1Q2AHyoLOpCfYF/Scaled-UI-and-Components"> https://www.figma.com/file/W2ZMhVYN1Q2AHyoLOpCfYF/Scaled-UI-and-Components</a></h4>

<h4 align="center">Imagem Exemplo Web com UI:</h4>

![Imagem exemplo:](https://i.imgur.com/AUDA98b.png)

Fonte de Texto: Cairo
https://fonts.google.com/specimen/Cairo

Cores e Tamanho dos Textos estão no Figma e nos próprios componentes.

As margens e paddings podem ser vistos usando o ALT + Ponteiro do Mouse sobre os Componentes no Figma

<h4 align="center">Imagem Exemplo de como visualizar distancia entre componentes:</h4>

![Imagem exemplo:](https://i.imgur.com/HjVwQYh.png)

Demais informações podem ser encontradas no Figma, inspecionando os componentes.

<h4 align="center">Imagem Exemplo de como inspecionar componentes:</h4>

![Imagem exemplo:](https://i.imgur.com/0wzbltU.png)

![Imagem exemplo:](https://i.imgur.com/vhwqzJW.png)

**Comment by rafael-g-depaulo** [comment]
Lembrando que tem que receber esse texto pela api do strapi, por meio de um hook de API que use o SWR. Isso provavelmente vai requerer o parse de texto por meio de linhas em branco e mapeamento disso em componentes de paragrafo. não é pra deixar a o texto hard-coded

**Comment by Jaxiii** [comment]
> Lembrando que tem que receber esse texto pela api do strapi, por meio de um hook de API que use o SWR. Isso provavelmente vai requerer o parse de texto por meio de linhas em branco e mapeamento disso em componentes de paragrafo. não é pra deixar a o texto hard-coded

Complementando aqui tmb, o espaçamento vai variar com a quantidade de palavras ou chars do parágrafo, mas como ainda não tem uma resposta definitiva da coordenação ainda n tem como definir uma logica final. Mas a ideia é o primeiro parágrafo aumentar em direção ao bottom do componente e o segundo paragrafo aumentar em direção ao top.

**Comment by Jaxiii** [comment]
UI Update.
Comentário inicial da issue atualizado com a UI.
