### ISSUE TITLE
Como usuário não-cadastrado, quero entrar na página do Quem Somos e ao rolar para baixo do Componente de Introdução desejo ver os demais Componentes de Apresentação

### ISSUE THREAD

**Issue by Jaxiii** [rafael-g-depaulo/labfaz#31]
#### De cima para baixo - O total de Componentes de Apresentação contém:
1. Componente de Apresentação 1
2. Componente de Apresentação 2
3. Componente de Apresentação 3

#### Da esquerda para direita - Componente de Apresentação do Quem Somos contém:
1. Parágrafos (No máximo dois, o primeiro alinhado com o topo, o segundo com o fundo (top e bottom), dependendo do tamanho da cada paragráfo pode haver apenas um - A lógica aqui será aprimorada/detalhada após resposta da quantidade de palavras/caracteres da coordenação)
1.1 Parágrafo 1 (acima do Parágrafo 2, separado pelo espaçamento definido no Figma)
1.2 Parágrafo 2 (abaixo do Parágrafo 1, separado pelo espaçamento definido no Figma)
2. Imagem de Introdução (Imagem)

**OBS**: Alguns artifícios de design ainda estão em estágio de aprovação pela coordenação.
Portanto recomendo seguir o padrão de design Wireframe que está atualmente no Figma.

#### Instruções detalhadas de design podem ser visualizadas no Figma pelos links:

* [Prototype] -> https://www.figma.com/proto/emttN5ixP7k3kw6b4F6zMW/Wireframe?node-id=239%3A76&scaling=scale-down&page-id=0%3A1
* [Layout] -> https://www.figma.com/file/emttN5ixP7k3kw6b4F6zMW/Wireframe?node-id=239%3A76

<h4 align="center">Imagem Exemplo:</h4>

![Imagem exemplo:](https://i.imgur.com/8emuydj.png)

### __________________________________________________________________________________________________________
<h2 align="center">User Interface - UI</h4>

<h4 align="center">Figma:</h4>
<h4 align="center">Pasta "UI"</h4>
<h4 align="center">Arquivo "Scaled UI Componentes"</h4>
<h4 align="center" ><a href="https://www.figma.com/file/W2ZMhVYN1Q2AHyoLOpCfYF/Scaled-UI-and-Components"> https://www.figma.com/file/W2ZMhVYN1Q2AHyoLOpCfYF/Scaled-UI-and-Components</a></h4>

<h4 align="center">Imagem Exemplo Web com UI:</h4>

![Imagem exemplo:](https://i.imgur.com/hH7dhlx.png)

Fonte de Texto: Cairo
https://fonts.google.com/specimen/Cairo

Cores e Tamanho dos Textos estão no Figma e nos próprios componentes.

As margens e paddings podem ser vistos usando o ALT + Ponteiro do Mouse sobre os Componentes no Figma

<h4 align="center">Imagem Exemplo de como visualizar distancia entre componentes:</h4>

![Imagem exemplo:](https://i.imgur.com/HjVwQYh.png)

Demais informações podem ser encontradas no Figma, inspecionando os componentes.

<h4 align="center">Imagem Exemplo de como inspecionar componentes:</h4>

![Imagem exemplo:](https://i.imgur.com/0wzbltU.png)

![Imagem exemplo:](https://i.imgur.com/vhwqzJW.png)

**Comment by rafael-g-depaulo** [comment]
Lembrando que tem que receber o texto pela api do strapi, por meio de um hook de API que use o SWR. não é pra deixar a o texto hard-coded

**Comment by Jaxiii** [comment]
> Lembrando que tem que receber o texto pela api do strapi, por meio de um hook de API que use o SWR. não é pra deixar a o texto hard-coded

Complementando aqui tmb, o espaçamento vai variar com a quantidade de palavras ou chars do parágrafo, mas como ainda não tem uma resposta definitiva da coordenação ainda n tem como definir uma logica final. Mas a ideia é o primeiro parágrafo aumentar em direção ao bottom do componente e o segundo paragrafo aumentar em direção ao top.

**Comment by Jaxiii** [comment]
UI Update.
Comentário inicial da issue atualizado com a UI.
