### ISSUE TITLE
Como usuário não-cadastrado, quero entrar na página do Quem Somos e ao rolar para baixo do Banner, Texto de Introdução e Componente de Apresentação desejo ver o Componente de Staff

### ISSUE THREAD

**Issue by Jaxiii** [rafael-g-depaulo/labfaz#52]
#### Da cima para baixo - Componente de Staff Contém:
1. Título
2. Subtítulo
3. Grid de Staff Cards ( 5xN - 5 Cards Horizontais por linha por N colunas )

#### De cima para baixo - O Staff Card contém:
1. Moldura
2. Imagem Circular com fundo circular
3. Texto centralizado no componente horizontalmente
4. Subtexto alinhado a esquerda
5. Parágrafo

**OBS**: Alguns artifícios de design ainda estão em estágio de aprovação pela coordenação.
Portanto recomendo seguir o padrão de design Wireframe que está atualmente no Figma.

#### Instruções detalhadas de design podem ser visualizadas no Figma pelos links:

* [Prototype] -> https://www.figma.com/proto/emttN5ixP7k3kw6b4F6zMW/Wireframe?node-id=239%3A76&scaling=scale-down&page-id=0%3A1
* [Layout] -> https://www.figma.com/file/emttN5ixP7k3kw6b4F6zMW/Wireframe?node-id=239%3A76

<h4 align="center">Imagens de Exemplo:</h4>

![Imagem exemplo:](https://i.imgur.com/MkoxdBg.png)

![Imagem exemplo:](https://i.imgur.com/PaujxYn.png)

### __________________________________________________________________________________________________________
<h2 align="center">User Interface - UI</h4>

<h4 align="center">Figma:</h4>
<h4 align="center">Pasta "UI"</h4>
<h4 align="center">Arquivo "Scaled UI & Components"</h4>
<h4 align="center" ><a href="https://www.figma.com/file/W2ZMhVYN1Q2AHyoLOpCfYF/Scaled-UI-and-Components"> https://www.figma.com/file/W2ZMhVYN1Q2AHyoLOpCfYF/Scaled-UI-and-Components</a></h4>

<h4 align="center">Imagem Exemplo Web com UI:</h4>

![Imagem exemplo:](https://i.imgur.com/7dF5JNk.png)

Fonte de Texto: Cairo
https://fonts.google.com/specimen/Cairo

Cores e Tamanho dos Textos estão no Figma e nos próprios componentes.

As margens e paddings podem ser vistos usando o ALT + Ponteiro do Mouse sobre os Componentes no Figma

<h4 align="center">Imagem Exemplo de como visualizar distancia entre componentes:</h4>

![Imagem exemplo:](https://i.imgur.com/HjVwQYh.png)

Demais informações podem ser encontradas no Figma, inspecionando os componentes.

<h4 align="center">Imagem Exemplo de como inspecionar componentes:</h4>

![Imagem exemplo:](https://i.imgur.com/0wzbltU.png)

![Imagem exemplo:](https://i.imgur.com/vhwqzJW.png)

**Comment by Zipudhe** [comment]
Essa UI já pode ser implementada com as cores ?

**Comment by rafael-g-depaulo** [comment]
> Essa UI já pode ser implementada com as cores ?

sim, @Zipudhe, já deve ser com as cores
