### ISSUE TITLE
Como usuário não-cadastrado, quero entrar na página do Blog e visualizar o Header e o Banner do Blog abaixo

### ISSUE THREAD

**Issue by Jaxiii** [rafael-g-depaulo/labfaz#53]
#### De cima para baixo - O Banner do Blog Contém:
1. Titulo (H1)
2. Subtítulo (H > 1)

Fundo - Background Image/Color ( Provável que seja uma imagem, porém pode usar Color por enquanto. )

**OBS**:  fonte, tamanho da fonte, imagem da logo, e paleta de cores ainda estão em estágio de aprovação pela coordenação. 
      Portanto recomendo seguir o padrão de design Wireframe que está atualmente no Figma.

#### Instruções detalhadas de design podem ser visualizadas no Figma pelos links:
* [Prototype] -> https://www.figma.com/proto/emttN5ixP7k3kw6b4F6zMW/Wireframe?node-id=239%3A76&scaling=scale-down&page-id=0%3A1
* [Layout] -> https://www.figma.com/file/emttN5ixP7k3kw6b4F6zMW/Wireframe?node-id=239%3A76

<h4 align="center">Imagem Exemplo Web:</h4>

![Imagem exemplo:](https://i.imgur.com/XP4pbIs.png)

<h4 align="center">Imagem Exemplo Mobile:</h4>

![Imagem exemplo:](https://i.imgur.com/1MifpxL.png)

### __________________________________________________________________________________________________________
<h2 align="center">User Interface - UI</h4>

<h4 align="center">Figma:</h4>
<h4 align="center">Pasta "UI"</h4>
<h4 align="center">Arquivo "Scaled UI & Components"</h4>
<h4 align="center" ><a href="https://www.figma.com/file/W2ZMhVYN1Q2AHyoLOpCfYF/Scaled-UI-and-Components"> https://www.figma.com/file/W2ZMhVYN1Q2AHyoLOpCfYF/Scaled-UI-and-Components</a></h4>

<h4 align="center">Imagem Exemplo Web com UI:</h4>

![Imagem exemplo:](https://i.imgur.com/QxsR5qV.png)

<h4 align="center">Imagem Exemplo Mobile com UI:</h4>

![Imagem exemplo:](https://i.imgur.com/4Ju6wUf.png)

Fonte de Texto: Cairo
https://fonts.google.com/specimen/Cairo

Cores e Tamanho dos Textos estão no Figma e nos próprios componentes.

As margens e paddings podem ser vistos usando o ALT + Ponteiro do Mouse sobre os Componentes no Figma

<h4 align="center">Imagem Exemplo de como visualizar distancia entre componentes:</h4>

![Imagem exemplo:](https://i.imgur.com/HjVwQYh.png)

Demais informações podem ser encontradas no Figma, inspecionando os componentes.

<h4 align="center">Imagem Exemplo de como inspecionar componentes:</h4>

![Imagem exemplo:](https://i.imgur.com/0wzbltU.png)

![Imagem exemplo:](https://i.imgur.com/vhwqzJW.png)

**Comment by priscila-eng** [comment]
Uma dúvida, não já tem essa página?

**Comment by rafael-g-depaulo** [comment]
> Uma dúvida, não já tem essa página?

Sim, @priscila-eng, mas antes a gente só tinha o wireframe. Agora temos a UI pra trabalhar em cima, e adicionar a estilização correta em vez do placeholder que tinha antes
