### ISSUE TITLE
Como usuário não-cadastrado, quero entrar na página do Blog clicar em um Post e ler a publicação 

### ISSUE THREAD

**Issue by Jaxiii** [rafael-g-depaulo/labfaz#55]
#### De cima para baixo - O Banner do Quem Somos Contém:
1. Titulo - Idêntico ao componente chamada para o post na pagina anterior e a direita divider e data, também idêntico ao componente da pagina anterior.
2. Subtítulo (H > 1) -  Idêntico ao componente chamada para o post na pagina anterior
3. Paragrafo -  Idêntico ao componente chamada para o post na pagina anterior
4. Imagem/Paragrafo 
4.1. Imagem/Paragrafo - A depender da publicação terá N imagens/parágrafos intercalados por decisão do autor 
Fundo - Background Image/Color ( Provável que seja uma imagem, porém pode usar Color por enquanto. )
5. Texto de Compartilhe
6. 4 Ícones distribuídos de forma horizontal para compartilhar nas redes sociais.

<h4 align="center">Imagem Exemplo:</h4>

![Imagem exemplo:](https://i.imgur.com/Y4RTFNi.png)

#### Instruções detalhadas de design podem ser visualizadas no Figma pelos links:

* [Prototype] -> https://www.figma.com/proto/emttN5ixP7k3kw6b4F6zMW/Wireframe?node-id=239%3A76&scaling=scale-down&page-id=0%3A1
* [Layout] -> https://www.figma.com/file/emttN5ixP7k3kw6b4F6zMW/Wireframe?node-id=239%3A76

### __________________________________________________________________________________________________________
<h2 align="center">User Interface - UI</h4>

<h4 align="center">Figma:</h4>
<h4 align="center">Pasta "UI"</h4>
<h4 align="center">Arquivo "Scaled UI Componentes"</h4>
<h4 align="center" ><a href="https://www.figma.com/file/W2ZMhVYN1Q2AHyoLOpCfYF/Scaled-UI-and-Components"> https://www.figma.com/file/W2ZMhVYN1Q2AHyoLOpCfYF/Scaled-UI-and-Components</a></h4>

<h4 align="center">Imagem Exemplo Web:</h4>

![Imagem exemplo:](https://i.imgur.com/Ui1KRHB.png)

<h4 align="center">Imagem Exemplo Mobile:</h4>

![Imagem exemplo:](https://i.imgur.com/PO9lQsX.png)

Fonte de Texto: Cairo
https://fonts.google.com/specimen/Cairo

Cores e Tamanho dos Textos estão no Figma e nos próprios componentes.

As margens e paddings podem ser vistos usando o ALT + Ponteiro do Mouse sobre os Componentes no Figma

<h4 align="center">Imagem Exemplo de como visualizar distancia entre componentes:</h4>

![Imagem exemplo:](https://i.imgur.com/HjVwQYh.png)

Demais informações podem ser encontradas no Figma, inspecionando os componentes.

<h4 align="center">Imagem Exemplo de como inspecionar componentes:</h4>

![Imagem exemplo:](https://i.imgur.com/0wzbltU.png)

![Imagem exemplo:](https://i.imgur.com/vhwqzJW.png)

**Comment by clarice42** [comment]
O estilo do texto muda de acordo com as tags que vão vir do markdown? Por exemplo, se for um texto simples (com a tag <p>) a fonte vai ser 18px, mas se for um subtítulo (<h2>) a fonte vai ser 24px. Isso aconteceria com links tbm? Eles teriam uma cor diferente do resto do texto, por exemplo?

**Comment by Jaxiii** [comment]
> O estilo do texto muda de acordo com as tags que vão vir do markdown? Por exemplo, se for um texto simples (com a tag p) a fonte vai ser 18px, mas se for um subtítulo (tag h2) a fonte vai ser 24px. Isso aconteceria com links tbm? Eles teriam uma cor diferente do resto do texto, por exemplo?

Hmmm... Na verdade eu não sei, tenho que ver com o @rafael-g-depaulo. O autor do post vai poder usar full Markdown? E tem que ter uma UI correspondente no texto do post? Ou da pra limitar de alguma forma?

**Comment by clarice42** [comment]
> > O estilo do texto muda de acordo com as tags que vão vir do markdown? Por exemplo, se for um texto simples (com a tag p) a fonte vai ser 18px, mas se for um subtítulo (tag h2) a fonte vai ser 24px. Isso aconteceria com links tbm? Eles teriam uma cor diferente do resto do texto, por exemplo?
> 
> Hmmm... Na verdade eu não sei, tenho que ver com o @rafael-g-depaulo. O autor do post vai poder usar full Markdown? E tem que ter uma UI correspondente no texto do post? Ou da pra limitar de alguma forma?

Se não for full markdown, vou ter que ver uma forma de limitar isso no strapi, porque ele fornece todas as opções de um editor de texto para o usuário. Mas no front é tranquilo de aplicar uma Ui para todos os textos, inclusive é assim que está por enquanto. Independente do tipo de texto que vem do strapi, ele é exibido com os estilos de um parágrafo normal.

**Comment by rafael-g-depaulo** [comment]
> > > O estilo do texto muda de acordo com as tags que vão vir do markdown? Por exemplo, se for um texto simples (com a tag p) a fonte vai ser 18px, mas se for um subtítulo (tag h2) a fonte vai ser 24px. Isso aconteceria com links tbm? Eles teriam uma cor diferente do resto do texto, por exemplo?
> > 
> > 
> > Hmmm... Na verdade eu não sei, tenho que ver com o @rafael-g-depaulo. O autor do post vai poder usar full Markdown? E tem que ter uma UI correspondente no texto do post? Ou da pra limitar de alguma forma?
> 
> Se não for full markdown, vou ter que ver uma forma de limitar isso no strapi, porque ele fornece todas as opções de um editor de texto para o usuário. Mas no front é tranquilo de aplicar uma Ui para todos os textos, inclusive é assim que está por enquanto. Independente do tipo de texto que vem do strapi, ele é exibido com os estilos de um parágrafo normal.

eu já falei com o coordenador de conteúdo do projeto. Nesse caso a opção mais fácil é só de conversar com os usuários e ensinar eles a não botar título.

No blog a gente vai renderizar parágrafos, texto em itálico, negrito, links, imagens, links do youtube (renderiza o player em vez de mostrar um link normal), listas ordenadas e não-ordenadas

**Comment by rafael-g-depaulo** [comment]
todas as outras features de markdown (títulos, principalmente) a gente não precisa se importar, porque o conteúdo que vai ser inserido no strapi não vai usar elas

**Comment by Jaxiii** [comment]
@rafael-g-depaulo o que você acha? Essa fonte, Cairo-AI, não tem itálico, mas tem Light e Extra-Light, que eu deixei reservado para servir como itálico. Alguma coisa ainda está faltando? Não consegui lembrar de todas as funcionalidades do MD que podem ser uteis para o blog. Só falar que eu coloca e atualizo a imagem desse comment.

<h4 align="center">Formatações de Textp</h4>

![Imagem exemplo:](https://i.imgur.com/tvsv36S.png)

**Comment by rafael-g-depaulo** [comment]
Umas coisas:
  - o player do youtube vai ser no mesmo esquema dessa imagem que vc botou depois do 1º parágrafo? se sim, não seria melhor deixar o player em 16x9 em vez de 2x1?
  - tem algumas coisas aí que eu não acho que vale o esforço de implementar e não são úteis o suficiente para os criadores de conteúdo:
    - strikethrough
    - citação

Sobre o itálico, eu acho que funciona usar o light/extra-light como itálico, mas ainda é bom fazer isso dentro de tags <i> por questão de acessibilidade

**Comment by Jaxiii** [comment]
> Umas coisas:
> 
> * o player do youtube vai ser no mesmo esquema dessa imagem que vc botou depois do 1º parágrafo? se sim, não seria melhor deixar o player em 16x9 em vez de 2x1?
> * tem algumas coisas aí que eu não acho que vale o esforço de implementar e não são úteis o suficiente para os criadores de conteúdo:
>   
>   * strikethrough
>   * citação
> 
> Sobre o itálico, eu acho que funciona usar o light/extra-light como itálico, mas ainda é bom fazer isso dentro de tags <i/> por questão de acessibilidade

- Eu acho que as imagens podem ser de qualquer tamanho, respeitando as margens. Mas por padrão coloquei exemplos com 2:1 e 16:9 agora que você comentou. 
- Adicionei o player em 16:9, que realmente é o ideal. 
- Retirei o strikethrough e citação

A imagem está atualizada com as modificações.

**Comment by rafael-g-depaulo** [comment]
massa, por mim a UI dessa feature tá perfeita agora. @clarice42 já pode implementar o que tá no figma e colocar exemplo de uso no storybook
