### ISSUE TITLE
Como usuário não cadastrado desejo entrar no www.labfaz.com.br e ver a página "Em construção"

### ISSUE THREAD

**Issue by Jaxiii** [rafael-g-depaulo/labfaz#58]
#### De cima para baixo - A Página de Em Construção contém:
1. Header
2. Componente Central
3. Texto

#### Da esquerda para direita - O Header contém:
1. Texto
2. Ícones de Mídias Sociais

#### Do fundo para a frente (eixo z) - O Componente Central contém:
1. Retângulo de Fundo
2. Triangulo alinhado a esquerda do retângulo
3. Imagens Circular com Bordas (pode ser feito com dois círculos)
4. Texto a direita da imagem
  
  
<h4 align="center">Imagem Exemplo:</h4>

![Imagem exemplo:](https://i.imgur.com/7af0cCE.png)

#### Instruções detalhadas de design podem ser visualizadas no Figma pelos links:

* [Prototype] -> https://www.figma.com/proto/emttN5ixP7k3kw6b4F6zMW/Wireframe?node-id=239%3A76&scaling=scale-down&page-id=0%3A1
* [Layout] -> https://www.figma.com/file/emttN5ixP7k3kw6b4F6zMW/Wireframe?node-id=239%3A76

### __________________________________________________________________________________________________________
<h2 align="center">User Interface - UI</h4>
  
    
<h4 align="center">Figma:</h4>
<h4 align="center">Pasta "UI"</h4>
<h4 align="center">Arquivo "Scaled UI Componentes"</h4>
<h4 align="center" ><a href="https://www.figma.com/file/W2ZMhVYN1Q2AHyoLOpCfYF/Scaled-UI-and-Components"> https://www.figma.com/file/W2ZMhVYN1Q2AHyoLOpCfYF/Scaled-UI-and-Components</a></h4>

<h4 align="center">Imagem Exemplo Web:</h4>

![Imagem exemplo:](https://i.imgur.com/7NyxpmH.png)

<h4 align="center">Imagem Exemplo Mobile:</h4>

![Imagem exemplo:](https://i.imgur.com/nWO2DRI.png)
  
  
  
Fonte de Texto: Cairo
https://fonts.google.com/specimen/Cairo

Cores e Tamanho dos Textos estão no Figma e nos próprios componentes.

As margens e paddings podem ser vistos usando o ALT + Ponteiro do Mouse sobre os Componentes no Figma
  
  
<h4 align="center">Imagem Exemplo de como visualizar distancia entre componentes:</h4>

![Imagem exemplo:](https://i.imgur.com/HjVwQYh.png)

Demais informações podem ser encontradas no Figma, inspecionando os componentes.

<h4 align="center">Imagem Exemplo de como inspecionar componentes:</h4>

![Imagem exemplo:](https://i.imgur.com/0wzbltU.png)

![Imagem exemplo:](https://i.imgur.com/vhwqzJW.png)

**Comment by rafael-g-depaulo** [comment]
> Algumas coisas estão com uns probleminhas.
> 
> 1. * [ ]  Quebra em telas grandes.
> 2. * [ ]  Texto quebrando em mobiles e falta de margem.
> 3. * [ ]  Colocar o Header de Redes e Mídias
> 4. * [ ]  Diminuir o texto quando for para small-desktop (720p)
> 

O 3. está funcionando, é só que o react tenta entrar em contato com o strapi pra pegar os links e só renderiza os que ele receber de volta. Os outros não são problemas que vale o esforço consertar, na minha opinião. Essa é uma tela temporária que só existe pra não ter isso como a nossa página principal até a gente lançar o site no final do projeto:

![image](https://user-images.githubusercontent.com/31452686/125453372-fdd2cbda-b396-49f7-a572-e0b4400a0027.png)

O que já existe em https://labfaz.com.br (assim que fizermos o update com a logo) já é, ao meu ver, mais que suficiente:

![image](https://user-images.githubusercontent.com/31452686/125453941-953abfbc-e874-41e0-b23b-494baac150bd.png)

 Eu não acho que vale a pena pra gente o esforço de melhorar essa página temporária. Ela não fica ideal em alguns tamanhos de tela meio comuns e em telas enormes quebra de forma bem drástica. Por mim isso é ok como uma página temporária que só existe pra ter \*alguma coisa\* enquanto o projeto rola mas o site ainda não foi lançado de verdade

**Comment by Jaxiii** [comment]
Beleza. Fechando o Issue novamente então.
