### ISSUE TITLE
Como usuário não cadastrado quero clicar no botão de cadastre-se do Header e ir para a Pagina de Cadastro e me registrar

### ISSUE THREAD

**Issue by Jaxiii** [rafael-g-depaulo/labfaz#67]
#### De cima para baixo - A Página de Cadastro contém:
1. Header
2. Componente de Cadastro
3. Footer

#### Da cima para baixo - Componente de Cadastro contém:
1. Texto Titulo
2. Componente Retangular

#### Da esquerda pra direita - Componente Retangular contém:
1. Texto Titulo
2. Componente Interno Retangular Esquerdo
3. Componente Interno Retangular Direito
4. Componente de Etapas

#### Do fundo para a frente (eixo z) - 2. Componente Interno Retangular Esquerdo contém:
1. Retângulo de Fundo
2. Form
3. Botão "voltar" a partir da 2 pagina.
#### Do fundo para a frente (eixo z) - 2. Componente Interno Retangular Direito contém:
1. Retângulo de Fundo
2. Form
3. Botão "avançar" ate a ultima pagina, depois "finalizar"
  
Fonte de Texto: Cairo
https://fonts.google.com/specimen/Cairo

<h4 align="center">Imagem Wireframe:</h4>

![Imagem exemplo:](https://i.imgur.com/CaEpZkF.png)

![Imagem exemplo:](https://i.imgur.com/ifyLO0H.png)

![Imagem exemplo:](https://i.imgur.com/fee0co0.png)

![Imagem exemplo:](https://i.imgur.com/3y8sLqM.png)

[![Image from Gyazo](https://i.gyazo.com/b13f7439cb8c5d36835eaa2460c08366.gif)](https://gyazo.com/b13f7439cb8c5d36835eaa2460c08366)

[![Image from Gyazo](https://i.gyazo.com/89be3aaadb7a4458aa43ac5df4d588b1.gif)](https://gyazo.com/89be3aaadb7a4458aa43ac5df4d588b1)

[![Image from Gyazo](https://i.gyazo.com/7eccc686d240b2b857d4b703794368b2.gif)](https://gyazo.com/7eccc686d240b2b857d4b703794368b2)

#### Instruções detalhadas de design podem ser visualizadas no Figma pelos links:

* [[Prototype]](https://www.figma.com/proto/emttN5ixP7k3kw6b4F6zMW/Wireframe-Web?page-id=0%3A1&node-id=856%3A3031&viewport=-6164%2C-1015%2C0.4193328320980072&scaling=contain)
* [[Layout]](https://www.figma.com/file/emttN5ixP7k3kw6b4F6zMW/Wireframe-Web?node-id=856%3A3031
)
### __________________________________________________________________________________________________________
<h2 align="center">User Interface - UI</h4>
  
    
<h4 align="center">**TODO**</h4>

**Comment by Jaxiii** [comment]
@IcaroRodrigues é possível o mobile ter uma ordem um pouco diferente do web?

**Comment by IcaroRodrigues** [comment]
@Jaxiii acredito que sim, os steps estão separados por componentes unitários, só criar a lógica se estar no mobile e colocar o step na ordem desejada

**Comment by rafael-g-depaulo** [comment]
@IcaroRodrigues eu tava conversando com o @Jaxiii, e achamos melhor ter 2 formatos válidos nos inputs de rede social. vc tem que checar que, por exemplo, a input do twitter ou tem o usuário no formato "@user_aqui" ou é um link do twitter, com o formato "https://(www. opcional)twitter.com/user_aqui" (tomando cuidado com o domínio

**Comment by IcaroRodrigues** [comment]
entendi, só não se é uma estratégia mt boa, pq em geral é mais fácil de o usuário apenas enviar o nickname dele da rede social em questão, então no caso do @usuário, só remover o @, se existir, lembrar que como a maioria dos usuários usam o celular para navegar, acaba que fica sendo incomodo ele mandar o link da rede social dele. E no final, no perfil dele, nós mesmos gerar o link com a tag por ex, <a href=`www.twitter.com/${twitter_nickname}`>Twitter</a>

**Comment by IcaroRodrigues** [comment]
Mas de qualquer forma, as duas estratégias podem ser feitas

**Comment by Jaxiii** [comment]
<h3 align="center">Mobile Update</h3>

#### Segue a mesma logica do componente web, porem com alguns inputs do form em ordem diferente do form web.
#### Navegar pelo Wireframe no figma é recomenado.

* [[Prototype]](https://www.figma.com/proto/vtom8xDBKNpvLaAcOgpzZj/Wireframe-Mobile?page-id=0%3A1&node-id=303%3A412&viewport=-281%2C265%2C0.410902202129364&scaling=scale-down&starting-point-node-id=303%3A412&show-proto-sidebar=1)
* [[Layout]](https://www.figma.com/file/vtom8xDBKNpvLaAcOgpzZj/Wireframe-Mobile?node-id=303%3A412)
### __________________________________________________________________________________________________________

![Imagem exemplo:](https://i.imgur.com/bAgT51n.png)

![Imagem exemplo:](https://i.imgur.com/tK46UvB.png)

[![Image from Gyazo](https://i.gyazo.com/b94205f16bd9ab1d5ad58cd4c14d47f4.gif)](https://gyazo.com/b94205f16bd9ab1d5ad58cd4c14d47f4)

**Comment by rafael-g-depaulo** [comment]
@Jaxiii @IcaroRodrigues @JoaoVictorCabraldeMelo eu recebi do Fanhu segunda feira uma alteração do form de cadastro. Ele mudou isso depois de receber um feedback de alguém que tentou usar o formulário original. No labfaz a gente quer deixar que pessoas que ainda não tem experiência possam se cadastrar, mas no formato atual é um usuário que não tem experiência tem que preencher um bando de coisas que ele não sabe, ou ficar pulando várias páginas do formulário sem responder nada.

Ele adicionou no form uma pergunta sobre se a pessoa já tem experiência profissional na área, e se ela responder não isso pula o equivalente das partes 5-8 no nosso wireframe Web de cadastro.

![image](https://user-images.githubusercontent.com/31452686/129063601-4fdc2f50-9f57-482e-a19e-b2d0f0e9466d.png)

A partir disso, e pensando em minimizar o nosso esforço de dev/design eu sugeri 2 soluções:
  - deixar as perguntas sobre experiência profissional como opcionais e fazer o usuário clicar em "avançar" várias vezes se ele não tiver experiência profissional prévia
    - pior UX, menos trabalho front/design
  - adicionar uma pergunta parecida no front e pular todas as questões sobre experiência profissional se o usuário responder sim e clicar em "avançar" (ou só esconder as inputs no mobile).
    - melhor UX, mais trabalho no front/design

Eu acho que além de tornar os campos opcionais isso não alteraria em nada no back. A gente recebeu esse feedback depois da reunião final de feedbacks da UX então tá super dentro da nossa autoridade tomar uma solução arbitrária que se encaixe melhor nas nossas necessidades internas. Se vcs tiverem outras ideias de como incorporar (ou não) essa mudança eu posso ouvir, mas na minha opinião as 2 opções acima já são minimamente viáveis, e só depende do @IcaroRodrigues decidir se rola o esforço de implementar a segunda opção ou se ele está apertado de mais e temos que ir com a primeira

**Comment by JoaoVictorCabraldeMelo** [comment]
De acordo com a modelagem do que está escrito no Back isso alteraria duas tabelas como nulas então teríamos que avaliar o custo e produção desse novo modelo. Dado minha situação atual eu poderia só implementar isto até 3 semanas acho que ficaria invíavel a não ser que tivessemos mais uma pessoa no back

**Comment by rafael-g-depaulo** [comment]
Então bora deixer

> De acordo com a modelagem do que está escrito no Back isso alteraria duas tabelas como nulas então teríamos que avaliar o custo e produção desse novo modelo. Dado minha situação atual eu poderia só implementar isto até 3 semanas acho que ficaria invíavel a não ser que tivessemos mais uma pessoa no back

Então bora deixar essa questão de lado por enquanto até arranjarmos tempo pra definir o custo. Vamos continuar até o final dessa semana focando nas features que já estão em desenvolvimento, e se der a gente volta e altera isso

**Comment by Jaxiii** [comment]
Vou providências umas telas com a opção de pular essa parte, fica a cargo de vocês a decisão de implementar a mudança, n demandaria muito de mim.

**Comment by IcaroRodrigues** [comment]
Concordo em deixar essa questão de lado por enquanto e tentarmos finalizar essas questões e conforme sobrar tempo, ver se da pra fazer as alterações desejadas @rafael-g-depaulo
