### ISSUE TITLE
Como usuário cadastrado ou não, ao interagir com o site/app e ocorrer um erro, desejo ser direcionado para a pagina de erro genérico.

### ISSUE THREAD

**Issue by Jaxiii** [rafael-g-depaulo/labfaz#88]
#### De cima para baixo - A Página de Error contém:
1. Header
2. Componente Central
3. Footer

#### Do fundo para a frente (eixo z) - O Componente Central contém:
1. Retângulo de Fundo
2. Triangulo alinhado a esquerda do retângulo
3. Imagens Circular com Bordas (pode ser feito com dois círculos)
4. Texto a direita da imagem, divido entre mensagem genérica e numero e mensagem de erro abaixo.

Similar ao Issue #58 e #70.    

<h4 align="center">Imagem Wireframe Figma</h4>

![Imagem exemplo:](https://i.imgur.com/CH7RbWP.png)

#### Instruções detalhadas de design podem ser visualizadas no Figma pelos links:

* [[Prototype]](https://www.figma.com/proto/emttN5ixP7k3kw6b4F6zMW/Wireframe-Web?page-id=0%3A1&node-id=1657%3A9322&viewport=-787%2C-3049%2C0.5379290580749512&scaling=scale-down&starting-point-node-id=1657%3A9322&show-proto-sidebar=1)
* [[Layout]](https://www.figma.com/file/emttN5ixP7k3kw6b4F6zMW/Wireframe-Web?node-id=1657%3A9322)

### __________________________________________________________________________________________________________
<h2 align="center">User Interface - UI</h4>
  
    
<h4 align="center">Figma:</h4>
<h4 align="center">Pasta "UI"</h4>
<h4 align="center">Arquivo "Scaled UI Componentes"</h4>
<h4 align="center" ><a href="https://www.figma.com/file/W2ZMhVYN1Q2AHyoLOpCfYF/Scaled-UI-and-Components?node-id=893%3A1371"> Figma</a></h4>

<h4 align="center">Imagem UI Web</h4>

![Imagem exemplo:](https://i.imgur.com/y4QtmFJ.png)

<h4 align="center">Imagem UI Mobile</h4>

<h4 align="center"><img src="https://i.imgur.com/cAHZ22s.png"></img></h4>

Fonte de Texto: Cairo
https://fonts.google.com/specimen/Cairo

**Comment by clarice42** [comment]
Na tela mobile é pra usar esse header e footer mesmo? Ou aqueles que têm navegação incluso, igual ao da tela web?

**Comment by rafael-g-depaulo** [comment]
eu acho bom usar o footer normal com navegação (na verdade melhor só botar a sua tela dentro de um componente de <Wireframe /> mesmo), mas o @Jaxiii tem a palavra final nisso
